render/go: include embedded images in Revised timestamp. (#62)
Previously, editing a .png or .pdf used as an image in an .md would
result in a .pdf that claimed the revision date/time-stamp of the .md
alone, hiding that the embedded image changed.

This commit makes render/go make an initial pandoc->typst conversion
and then use typst to dump the documents' dependencies, and then uses
those dependencies in calculating the Revised date/time-stamp.

Also added floor_door/door_manual.pdf to .gitignore since apparently
it was missed in 1187f0c1.

diff --git a/render/go b/render/go
--- a/render/go
+++ b/render/go
@@ -4,9 +4,9 @@
 
 set -eu -o pipefail
 
-if [[ "$#" != 1 ]]; then
+if [[ "$#" != 1 || ! -f "$1" ]]; then
     echo "Usage: $0 <path/to/file>.md" >&2
-    echo "Example: $0 'Cut_Lists/Interior Panels.md'" >&2
+    echo "Example: $0 'Cut_Lists/Interior_Panels_Cut_List.md'" >&2
     exit 1
 fi
 
@@ -26,18 +26,49 @@ function capitalize() {
 INPUT_FILE="$(basename "$INPUT")"
 INPUT_DIR="$(dirname "$(realpath --relative-to="$PWD" "$INPUT")")"
 TITLE="$(capitalize "$INPUT_DIR") \\ $(capitalize "$INPUT_FILE")"
-REVISION_DATE="$(git log -1 --format="%cd" --date=format:"%Y-%m-%d %H:%M:%S" -- "${INPUT}")"
-CREATION_TIMESTAMP="$(git log -1 --format="%ct" -- "$INPUT")"
-# Handle new .md files that have no git log yet.
-REVISION_DATE="${REVISION_DATE:-0000-00-00 00:00:00}"
-CREATION_TIMESTAMP="${CREATION_TIMESTAMP:-0}"
 
+RUNNER="$(type -p docker || type -p podman)"
+function dockerRun() {
+    "$RUNNER" run --rm \
+              -v "$PWD":/s:z \
+              -w "/s/$INPUT_DIR" \
+              -e FOOTER \
+              -e TYPST_FONT_PATHS=/s/render/Carlito \
+              --entrypoint=/bin/sh \
+              ghcr.io/pandoc/typst:3.8.3 `# Update ./all when this changes!` \
+              -c \
+              "$@"
+}
+
+RELATIVE_RENDER_PATH="$(realpath --relative-to="$INPUT_DIR" "$PWD/render")"
+
+declare -a common_flags
+common_flags=(pandoc -d "${RELATIVE_RENDER_PATH}/pandoc-defaults.yaml" --template "${RELATIVE_RENDER_PATH}/typst-header.typ")
+
+# Extract from $INPUT any images it embeds, to account for in the last-revision timestamp.
+# Needs to be a dockerRun separate from the typst invocation because the container doesn't have git.
+export TEMPTYP=".TEMP.$$.typ"
+extract_out="$(dockerRun "trap 'rm -f ${TEMPTYP}' EXIT; \
+                         ${common_flags[*]} \
+                  --to typst '$INPUT_FILE' -o ${TEMPTYP} \
+        && typst compile --root /s -f pdf --deps /dev/stdout ${TEMPTYP} /dev/null | \
+        `# Poor-man's jq to parse out deps' paths from typst json output.` \
+        sed -e 's/^{\"inputs\":\[//' -e 's/]}$//' -e 's/^\"//' -e s'/\"$//' -e 's/\",\"/\n/g' | \
+        `# Strip leading ../ to get back to repo-root-relative paths.` \
+        sed -e 's#^\(\.\./\)*##' | \
+        grep -v \"$TEMPTYP\" | \
+        sort -n")" \
+    || { echo "$0: failed extracting embedded images from $INPUT" >&2; exit 1; }
+unset TEMPTYP
+mapfile -t IMAGE_PATHS < <(printf '%s' "$extract_out")
+
+last_modification="$(git log -1 --format="%cd|%ct" --date=format:"%Y-%m-%d %H:%M:%S" -- "${INPUT}" "${IMAGE_PATHS[@]}")"
+IFS='|' read -r REVISION_DATE CREATION_TIMESTAMP <<< "${last_modification:-0000-00-00 00:00:00|0}" # Handle new .md files that have no git log yet.
 OUTPUT_FILE="${INPUT_FILE/%.md/.pdf}"
 export FOOTER="Revised $REVISION_DATE"
 
 declare -a flags
-RELATIVE_RENDER_PATH="$(realpath --relative-to="$INPUT_DIR" "$PWD/render")"
-flags=(pandoc -d "${RELATIVE_RENDER_PATH}/pandoc-defaults.yaml" --template "${RELATIVE_RENDER_PATH}/typst-header.typ")
+flags=("${common_flags[@]}")
 flags+=("--pdf-engine-opt=--root=/s")
 flags+=("'$INPUT_FILE'" -o "'$OUTPUT_FILE'")
 flags+=(-H '<(echo "#set page(footer: context { if counter(page).get().first() > 0 [$FOOTER #h(1fr) [#counter(page).display() / #counter(page).final().first()]] })")')
@@ -48,13 +79,4 @@ fi
 # Make re-runs idempotent; typst embeds the "current" time into the .pdf, so set that "current" time to the last modification time of the input file.
 flags+=("--pdf-engine-opt=--creation-timestamp=$CREATION_TIMESTAMP")
 
-RUNNER="$(type -p docker || type -p podman)"
-"$RUNNER" run --rm \
-       -v "$PWD":/s:z \
-       -w "/s/$INPUT_DIR" \
-       -e FOOTER \
-       -e TYPST_FONT_PATHS=/s/render/Carlito \
-       --entrypoint=/bin/sh \
-       ghcr.io/pandoc/typst:3.8.3 `# Update ./all when this changes!` \
-       -c \
-       "${flags[*]}"
+dockerRun "${flags[*]}"
